name: release
on: [ workflow_dispatch ]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true
          cache: true
      - name: Set Up UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
      - name: Dependencies
        run: go get -d -v ./...
      - name: Install
        run: go install -v ./...
      - name: Make Build Script Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./build.sh
      - name: Build
        run: ./build.sh
      - name: Upload
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: 1.0.0
          files: |
            build/*